services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: {{POSTGRES_DB}}
      POSTGRES_USER: {{POSTGRES_USERNAME}}
      POSTGRES_PASSWORD: {{POSTGRES_PASSWORD}}
    volumes:
      - fitcore-pgdata:/var/lib/postgresql/data

volumes:
  fitcore-pgdata:
